local SG = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer:WaitForChild("PlayerGui"))
SG.Name = "KurdiX_GUI"
local F = Instance.new("Frame", SG)
F.Size = UDim2.new(0, 200, 0, 100)
F.Position = UDim2.new(0.5, -100, 0.5, -50)
F.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
local L = Instance.new("TextLabel", F)
L.Size = UDim2.new(1, 0, 1, 0)
L.Text = "KurdiX Hub Loaded!"
L.TextColor3 = Color3.fromRGB(255, 255, 255)
